version: "3.4"

networks:
  questionnaire:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qr.app
    volumes:
      - ./src:/app/src
    ports:
    - 3000:3000
    networks:
      - questionnaire

  mongo:
    image: mongo:4.4
    restart: always
    container_name: qr.mongo
    env_file:
      - .development.env
    ports:
    - 27020:27017
    networks:
      - questionnaire
