version: "3.4"

networks:
  questionnaire:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qr.app
    volumes:
      - ./src:/app/src
    ports:
    - 3000:3000
    networks:
      - questionnaire

  mongo:
    image: mongo:4.4
    restart: always
    container_name: qr.mongo
    env_file:
      - .development.env
    volumes:
    - ./docker-compose/mongo/data:/data/db
    ports:
    - 27020:27017
    networks:
      - questionnaire

  mongo-express:
    image: mongo-express:0.54
    container_name: qr.mexpress
    restart: always
    ports:
      - 10081:8081
    environment:
      - ME_CONFIG_MONGODB_AUTH_DATABASE=test
      - ME_CONFIG_MONGODB_AUTH_USERNAME=nik
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=1234
      - ME_CONFIG_MONGODB_ADMINUSERNAME=nik
      - ME_CONFIG_MONGODB_ADMINPASSWORD=1234
    networks:
      - questionnaire